# -*- coding: utf-8 -*-
"""Weekly_assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sd6oqMzT-dReSZKWa3SfUHmuq2JI09UG

1.Print the input text without vowels using List comprehensions

input = 'hai'

Expected output = h
"""

def cons(a):
  b=['a','e','i','o','u','A','E','I','O','U']
  for i in a:
    if i not in b:
      print(i,end="")
a=input('Enter the Word: ')
cons(a)

"""2 . Print only vowels from the text using List comprehensions

input = data

Expected output = dt

"""

def vow(a):
  b=['a','e','i','o','u','A','E','I','O','U']
  for i in a:
    if i in b:
      print(i,end='')
a=input('Enter the input: ')
vow(a)

""" 3.print each valu from the list with its index

input = [10,11,50,34]

Expected output = [100 , 111 , 502 , 343]

"""

def index(a):
  for i,j in enumerate(a):
   print(j,end=f'{i} ')
a=[10,11,50,34]
index(a)

"""4 . This is a Python Program to print all integers that aren’t divisible by either 2 or 3 and lies between 1 and 50."""

def div():
  b=[]
  for i in range(1,51):
    if i%2!=0 and i%3!=0:
      b.append(i)
  return b
div()

"""5 . The program takes in an integer and prints the smallest divisor of the integer."""

def small(a):
  b=[]
  for i in range(1,a):
    if a%i==0:
      b.append(i)
  return b

a=int(input('Enter integer: '))
small(a)

"""6 . Write a Python program to check if it is a strong number or not .

"""

def strong(a):
  c=a
  sum=0
  while a>0:
    res=a%10
    product=1
    for i in range(1,res+1):
      product=product*i
    sum=sum+product
    a=a//10
  if c==sum:
    return 'Strong Number'
  else:
    return 'Not a Strong Number'


a=int(input('Enter a number:'))
strong(a)

"""7 . Write a Python program that takes input from the user and displays that input back in upper and lower cases."""

def string(a):
  b=a.upper()
  c=b.lower()
  return b,c
a=str(input('Enter the string: '))
string(a)

"""8 . Write a Python program to remove spaces from a given string

input = united states

output = unitedstates

"""

def remove_spaces(a):
  for i in a:
    if i ==' ':
      continue
    else:
      print(i,end="")
a=str(input('Enter the string:'))
remove_spaces(a)

"""9 . Write a Python program to capitalize first and last letters of each word of a given string."""

def word(a):
  return(str(a[0].capitalize()+a[1:(len(a)-1)]+a[-1].capitalize()))
a=str(input('Enter a string:'))
word(a)

"""10 . write a python program to find length of a string but should not use  len keyword"""

def len(a):
  count=0
  for i in a:
    count=count+1
  return count
a=str(input('Enter the string:'))
len(a)